apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-env-var
  namespace: default
data:
  DB_HOST: mongo-mongodb.default.svc.cluster.local
  DB_PORT: "27017"
  DB_DATABASE: sample


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
    version: latest
  name: nodejs-latest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
      version : latest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: v1-03072019
        app: nodejs
        version : latest
    spec:
      containers:
      - name: nodejs-deployment-latest
        image: developerrohitkhatri/sample-nodejs-api
        imagePullPolicy: Always
        resources:
          limits:
            memory: 700Mi
        envFrom:
          - configMapRef:
              name: nodejs-env-var
        env:
        - name: APPLICATION_PORT
          value: "3000"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: nodejs-db-mongo
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: nodejs-db-mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
    version: latest
    type : service
  name: nodejs-internal-latest
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: nodejs
    version: latest
  sessionAffinity: None
  type: ClusterIP
